default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: angipl_2018_development

test:
  <<: *default
  database: angipl_2018_test

production:
  <<: *default
  database: angipl_2018_production
  username:
  password:
