default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: angipl_remake_development

test:
  <<: *default
  database: angipl_remake_test

production:
  <<: *default
  database: angipl_remake_production
  username:
  password:
